Fix code typo in reports.py
Lonami/TelethonianBotExt pull request #51
Opened 2021-03-11 11:07 UTC by nitanmarcel

No idea why I used `pass` while `continue` was the right thing to use. `pass` skips the whole function while `continue` skips the current iteration

2021-03-11 11:20 UTC, tulir requested changes
This looks like `pass` and `continue` do the exact same thing. I think `pass` is better

2021-03-11 12:39 UTC, nitanmarcel commented
> This looks like `pass` and `continue` do the exact same thing. I think `pass` is better

If you notice the last line it should send a message saying that x reported y but it doesn't send it. Instead it's finishes the "task" when it hits an exception in the iteration

2021-03-11 12:44 UTC, nitanmarcel commented
![IMG_20210311_144136.jpg](https://user-images.githubusercontent.com/41646249/110789117-3150d700-8278-11eb-882f-965f49cf1eda.jpg)

@tulir see above. I haven't actually used python for a long time, even at the time I was making the PR and some things slipped thought my head

2021-03-11 12:44 UTC, tulir commented
The last line is outside the `for`, pass vs continue doesn't affect it

2021-03-11 12:52 UTC, nitanmarcel commented
> The last line is outside the `for`, pass vs continue doesn't affect it

Hmm my bad here. Tho I still don't understand why the last line isn't called

2021-03-11 12:54 UTC, tulir commented
Some exception other than `UserIsBlockedError` or `ValueError` maybe? Have you asked lonami to check the logs?

2021-03-11 13:00 UTC, nitanmarcel commented
> Some exception other than `UserIsBlockedError` or `ValueError` maybe? Have you asked lonami to check the logs?

Not really, I'mma ask him now if he can check it. Tho the thing is that in my test everything went right. I blocked the bot, and I've also trying with lonami's username which hasn't talked with the bot before. But maybe I've missed something

@Lonami could you look? Thanks.

2021-03-13 23:00 UTC, Lonami commented
File "/home/lonabots/Telethonian/plugins/reports.py", line 77, in report (`await bot.send_message(`) was failing with `telethon.errors.rpcerrorlist.PeerIdInvalidError` the 11th.

2021-03-14 16:06 UTC, nitanmarcel commented
> File "/home/lonabots/Telethonian/plugins/reports.py", line 77, in report (`await bot.send_message(`) was failing with `telethon.errors.rpcerrorlist.PeerIdInvalidError` the 11th.

Wtf? That's not a blocked user nor someone who never talked with the bot

2021-03-14 17:05 UTC, Lonami commented
Why don't you just `except RPCError`?

2021-03-15 08:28 UTC, nitanmarcel commented
> Why don't you just `except RPCError`?

Good idea, I'll do it today

2021-03-24 11:55 UTC, nitanmarcel commented
> 
> 
> Why don't you just `except RPCError`?

@Lonami done. Looks like I was wrong:

* `ValueError` was returned if the bot hasn't seen the bot before (I still kept this just in case it somehow happens even if the bot can't see the user
* `UserIsBlockedError` it's returned when the user stops the bot
* `PeerIdInvalidError` it's returned if the user didn't started the bot at least one time

2021-03-24 12:47 UTC, merged